import { classify, noteFault, noteOk } from "@/lib/health";

// ═══ A SEARCH BOX THAT BEHAVES LIKE A SEARCH BOX ══════════════════════════
//
// The first cut used Places TEXT SEARCH, which answers "find me this thing"
// once you have finished describing it. That is the wrong verb for a field
// somebody is typing into: it meant nothing happened until three characters
// were in, then a pause, then a list — and only when the local area table had
// come up empty. Two different behaviours in one box, neither of them what a
// search box does.
//
// AUTOCOMPLETE is the right call, and not only because it feels better:
//
//   · SUGGESTIONS PER KEYSTROKE, from two characters, which is what "like
//     Google" actually means — the list narrows while you type rather than
//     arriving after you stop.
//   · CHEAPER, despite firing far more often. Autocomplete is billed per
//     SESSION, not per request: every keystroke from the first letter to the
//     moment somebody picks a result shares one token and bills once. Text
//     search per keystroke would have been the expensive way to do this.
//   · The coordinates are fetched ONCE, on selection, not for five candidates
//     nobody chose.
//
// The session token is what makes that pricing hold, so it is generated by the
// CLIENT at the start of a search and passed through unchanged to both calls —
// generating one per request here would silently bill every keystroke
// separately, which is the same money with none of the benefit.
//
// DELIBERATELY NOT FILTERED TO FOOD, unlike the saved-post resolver. There the
// filter stops a caption resolving to a shopping mall; here the mall IS the
// answer, because that is where the person will be standing.

/** A suggestion, before anybody has committed to it. No coordinates yet. */
export interface Suggestion {
  /** Google's opaque id, exchanged for coordinates only if this one is picked. */
  id: string;
  /** "Micron Semiconductor Asia" — the bold half in a Maps dropdown. */
  main: string;
  /** "1 North Coast Drive" — the half that tells two branches apart. */
  secondary: string | null;
}

/** A place somebody actually chose. */
export interface Located {
  label: string;
  address: string | null;
  lat: number;
  lng: number;
}

export const geocodeConfigured = (): boolean => Boolean(process.env.GOOGLE_PLACES_API_KEY);

/** Singapore only. A lunch plan is never in another country, and the region
    code is a cleaner instrument than a bounding box — it excludes Johor
    without also clipping Tuas. */
const REGION = ["sg"];

/** Bias toward the middle of the island so nearby matches rank first. */
const SG_CENTRE = { latitude: 1.3521, longitude: 103.8198 };

/**
 * Suggestions for what somebody is typing. Returns [] on every failure path —
 * the caller still has the local area table.
 */
export async function suggestPlaces(input: string, sessionToken: string): Promise<Suggestion[]> {
  const key = process.env.GOOGLE_PLACES_API_KEY;
  const q = input.trim();
  // Two characters is where a suggestion starts being a suggestion rather than
  // a list of the whole island.
  if (!key || q.length < 2) return [];

  try {
    const res = await fetch("https://places.googleapis.com/v1/places:autocomplete", {
      method: "POST",
      signal: AbortSignal.timeout(3500),
      headers: { "Content-Type": "application/json", "X-Goog-Api-Key": key },
      body: JSON.stringify({
        input: q.slice(0, 120),
        includedRegionCodes: REGION,
        // BIAS here, not restrict: the region code has already done the
        // excluding, and this only decides what sorts to the top.
        locationBias: { circle: { center: SG_CENTRE, radius: 30000 } },
        sessionToken,
      }),
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      noteFault("places", classify(body, res.status), `autocomplete ${res.status} ${body}`);
      return [];
    }

    const data = (await res.json()) as {
      suggestions?: Array<{
        placePrediction?: {
          placeId?: string;
          text?: { text?: string };
          structuredFormat?: { mainText?: { text?: string }; secondaryText?: { text?: string } };
        };
      }>;
    };
    noteOk("places");

    const out: Suggestion[] = [];
    for (const s of data.suggestions ?? []) {
      const p = s.placePrediction;
      const main = p?.structuredFormat?.mainText?.text ?? p?.text?.text;
      if (!p?.placeId || !main) continue;
      out.push({
        id: p.placeId,
        main: main.slice(0, 40),
        // Singapore's postal suffix is noise in a 390px sheet; the road is the
        // part that distinguishes.
        secondary:
          p.structuredFormat?.secondaryText?.text
            ?.replace(/,?\s*Singapore(\s*\d{6})?$/i, "")
            .slice(0, 52) || null,
      });
    }
    return out.slice(0, 6);
  } catch (e) {
    noteFault("places", classify(e), e instanceof Error ? e.message : String(e));
    return [];
  }
}

/**
 * Exchange a chosen suggestion for coordinates. One call, once, at the moment
 * of selection — closing the session the suggestions opened.
 */
export async function placeById(id: string, sessionToken: string): Promise<Located | null> {
  const key = process.env.GOOGLE_PLACES_API_KEY;
  if (!key || !id.trim()) return null;

  try {
    const res = await fetch(
      `https://places.googleapis.com/v1/places/${encodeURIComponent(id)}?sessionToken=${encodeURIComponent(sessionToken)}`,
      {
        signal: AbortSignal.timeout(3500),
        headers: {
          "X-Goog-Api-Key": key,
          // The three fields the plan bar needs and nothing else — every extra
          // one moves this into a pricier SKU for data nobody reads.
          "X-Goog-FieldMask": "displayName,location,formattedAddress",
        },
      },
    );

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      noteFault("places", classify(body, res.status), `details ${res.status} ${body}`);
      return null;
    }

    const p = (await res.json()) as {
      displayName?: { text?: string };
      location?: { latitude?: number; longitude?: number };
      formattedAddress?: string;
    };
    noteOk("places");

    const lat = p.location?.latitude;
    const lng = p.location?.longitude;
    if (!p.displayName?.text || typeof lat !== "number" || typeof lng !== "number") return null;

    return {
      label: p.displayName.text.slice(0, 40),
      address: p.formattedAddress?.replace(/,?\s*Singapore\s*\d{6}$/i, "").slice(0, 60) || null,
      lat,
      lng,
    };
  } catch (e) {
    noteFault("places", classify(e), e instanceof Error ? e.message : String(e));
    return null;
  }
}
